---
ID: "7ccf3a8b-7ab6-4da2-b410-4777982a16b7"
Parent: "4ff2646c-2b0f-428f-b9a0-d6ea531de713"
Template: "dd22f1b3-bd87-4db2-9e7d-f7a496888d43"
Path: /sitecore/system/Modules/PowerShell/Script Library/Click Click Launch/Functions/Site 2 Configure Rendering Host
SharedFields:
- ID: "b1a94ff0-6897-47c0-9c51-aa6acb80b1f0"
  Hint: Script
  Value: |
    function Invoke-Step {
        [CmdletBinding()]
        param(
            [Parameter(Mandatory = $true, Position = 0)]
            [Sitecore.XA.JSS.Foundation.Scaffolding.Models.CreateNewJSSSiteModel]$Model
        )
    
        begin {
            Write-Log "Cmdlet Setup Site Grouping Item" -Log "INFO"
            Write-Verbose "Cmdlet Setup Site Grouping Item"
            Write-Verbose "Cmdlet Invoke-ModuleScriptBody - Begin"
        }
        
        process {
            Write-Verbose "Cmdlet Invoke-ModuleScriptBody - Process"
            [Item]$SiteLocation = $Model.SiteLocation
            $sitePath = "$($SiteLocation.Paths.Path)/$($Model.SiteName)"
    
            Write-Log "Reset the start item and the rendering host" -Log "INFO"
            # reset the start item and the rendering host
            $siteGrouping = Get-Item -Path "$sitePath/Settings/Site Grouping/$($Model.SiteName)" -Language $Site.Language
            $siteGrouping.RenderingHost = "kit-nextjs-location-starter"
        }
        
        end {
            Write-Log "Cmdlet Invoke-ModuleScriptBody - End" -Log "INFO"
        }
    }
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "9f1284e2-ba43-4c7d-bbc1-53323e5caf77"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250626T115631Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\richard.seal@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\richard.seal@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "dca8ac4c-6a98-436d-8e3b-90584e5c1aeb"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\richard.seal@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250626T115631Z
