---
ID: "aeaf9cc7-810d-4187-8143-673963de76c4"
Parent: "4e232f8b-59a1-46b4-9ea2-9645ee2b83dc"
Template: "4e232f8b-59a1-46b4-9ea2-9645ee2b83dc"
Path: "/sitecore/templates/Project/click-click-launch/Sites/Site 3/MegaMenuItem/Rendering Parameters/MegaMenuItem Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "59543634-fd14-4748-bece-74ab38c417b8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250612T093815Z
