---
ID: "f9f6885b-3d1c-48c3-852a-9daab4590af1"
Parent: "8b8335ff-7082-4d8f-a1a8-4cfe82472b39"
Template: "8b8335ff-7082-4d8f-a1a8-4cfe82472b39"
Path: "/sitecore/templates/Project/click-click-launch/Components/CTA Sectoins/Rendering Parameters/CallToAction Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1b03d940-a6dc-4c01-8bcd-dc65dcf8fa75"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\richard.seal@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250216T133713Z
