---
ID: "9b767d0f-be71-4ac3-87c5-e74e995d7676"
Parent: "4f118695-0fa3-4943-8835-64ddc8f8b611"
Template: "267d9ac7-5d85-4e9d-af89-99ab296cc218"
Path: "/sitecore/templates/Branches/Project/click-click-launch/Alaris/Add Dictionary Items/Product"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250319T184533Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "abe4d652-6fee-4af3-a445-2c6641d474d2"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250319T184533Z
