---
ID: "2d1465cb-6f3a-4a69-b0a7-24748ff4e49c"
Parent: "4b39645f-f45a-4099-817a-60a20e48da25"
Template: "4b39645f-f45a-4099-817a-60a20e48da25"
Path: "/sitecore/templates/Project/click-click-launch/Sites/Site 3/HeaderST/Rendering Parameters/HeaderST Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "edaaf116-d3f4-49bf-80de-d39822b6d047"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250612T085912Z
