---
ID: "762d30e7-c4ce-4f0a-be69-23a16863d881"
Parent: "b355f1cf-90b3-48c7-ad65-b85bd5eaaa5f"
Template: "b355f1cf-90b3-48c7-ad65-b85bd5eaaa5f"
Path: "/sitecore/templates/Project/click-click-launch/Sites/Site 3/TextSlider/TextSlider Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {BF764C63-DF4B-460F-BF87-B4F16733A4FD}
    {B355F1CF-90B3-48C7-AD65-B85BD5EAAA5F}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "240db44b-0909-4870-a275-8d1c048aca95"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1a9293d5-e72d-45de-a3e0-0b511df238a1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250528T135956Z
