---
ID: "c58b3a3e-5a70-4568-825f-f0bf316ec02d"
Parent: "58041043-7bea-44f0-b1b8-08e4ea7054f4"
Template: "58041043-7bea-44f0-b1b8-08e4ea7054f4"
Path: "/sitecore/templates/Project/click-click-launch/Components/Page Content/Text/__Standard Values"
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{A053ED9F-4099-4682-9411-2B4C98E481E4}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "dfac6258-8252-4bac-be3a-aef70b99b3b0"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250717T134034Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\anton.kechashin@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\anton.kechashin@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7a3364ca-18ca-413c-925e-cfa62da12532"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\anton.kechashin@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250717T134044Z
