---
ID: "dfa396f4-ec94-4311-9599-72cea2bb0d54"
Parent: "46d29149-02ab-4ef1-af37-e765e26a7e2f"
Template: "46d29149-02ab-4ef1-af37-e765e26a7e2f"
Path: "/sitecore/templates/Project/click-click-launch/Components/Product/Product Listing/__Standard Values"
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{A053ED9F-4099-4682-9411-2B4C98E481E4}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "5469e400-a7d9-4f70-b2fe-3e7247d6fca6"
Languages:
- Language: en
  Versions:
  - Version: 2
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250319T172123Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b74a15fb-8063-4796-ade6-c1b85d53420c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\anton.kechashin@sitecore.com
    - ID: "d5b23eab-5eda-481f-8aa5-f81df32cc446"
      Hint: title
      Value: $name
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250717T134246Z
