---
ID: "4d9cf8a8-38a7-486f-8f5a-a5dc2bc9b7c4"
Parent: "07ec4360-f49a-48dd-ab46-5a5fa89cde7b"
Template: "07ec4360-f49a-48dd-ab46-5a5fa89cde7b"
Path: "/sitecore/templates/Project/click-click-launch/Components/Page Content/Logo Tab/__Standard Values"
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: /~/icon/control/32x32/tabs.png
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{2B90BF80-BB08-44A2-AD76-600AD0ED915B}"
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{A053ED9F-4099-4682-9411-2B4C98E481E4}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "e2b5fccb-5cc6-48d5-8c8f-cc1adbff407d"
Languages:
- Language: en
  Versions:
  - Version: 2
    Fields:
    - ID: "121f4e8b-049b-4c7e-9f73-fddf43f4c2a9"
      Hint: titleRequired
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240606T192503Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ac6edfaf-7067-42b2-9633-d3e688fa5cd4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\anton.kechashin@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250717T134017Z
