---
ID: "0c038c3a-481b-480c-ad8b-4fdef74cca08"
Parent: "d1cfd3ce-f1df-4746-8260-f7cea60e2029"
Template: "83746e54-66fe-4fd4-b79d-ff3fd4acd903"
Path: "/sitecore/templates/Branches/Project/click-click-launch/Components/Page Headers/Test Hero Enumerations/$name/Color Schemes/default"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20241114T181719Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0fed3b55-1dcd-47d5-af5b-5b2b24432215"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20241114T181719Z
