---
ID: "1f8b1951-17bc-4af9-bf4d-f12401bfec81"
Parent: "8001017f-9ee9-48f2-b2d3-94ef6ec1fa09"
Template: "fd2059fd-6043-4dfe-8c04-e2437ce87634"
Path: "/sitecore/templates/Branches/Project/click-click-launch/SYNC/Add Partial Designs/Global/ProductContent"
SharedFields:
- ID: "55faae90-3bba-4f7f-96fe-13c3f40055ff"
  Hint: Signature
  Value: productcontent
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediaid="{86397976-8410-42C2-82F3-B494526BF166}" />
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "ac650092-e3fa-435a-95b8-8023e718bc6d"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{D016AE46-06B3-446F-A58D-8FF57E6C69CE}"
              p:before="*"
              s:id="{1DF6DDA7-5669-4172-A9B6-1616689733EA}"
              s:par="GridParameters=%7BF61E01E9-711A-4C99-AE30-4E28463E1DF7%7D&amp;FieldNames&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=1"
              s:ph="headless-main" />
            <r
              uid="{7D9812A8-52CF-41FA-AE5D-FEE9D21CC944}"
              p:after="r[@uid='{D016AE46-06B3-446F-A58D-8FF57E6C69CE}']"
              s:id="{7A1D9A21-B8D7-42F9-9B0B-92ABF8D1974F}"
              s:par="GridParameters=%7BF61E01E9-711A-4C99-AE30-4E28463E1DF7%7D&amp;FieldNames&amp;BackgroundImage&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=2"
              s:ph="headless-main" />
            <r
              uid="{AEE03D81-5DB2-4C44-A2C3-7CDE5316A3EB}"
              p:after="*[1=2]"
              s:ds="local:/Data/SignupBanner 1"
              s:id="{EF8925C3-D106-4187-9BC4-3C19A213AE75}"
              s:par="GridParameters=%7BF61E01E9-711A-4C99-AE30-4E28463E1DF7%7D&amp;FieldNames=%7BDEB21B00-134A-4EA2-8037-B91B4540859B%7D&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=3"
              s:ph="headless-main" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250603T043450Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c098b8c9-8349-4535-8d1d-99f76c6fcce9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\richard.seal@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250703T154234Z
