---
ID: "504ea2be-9689-41cb-bcef-281131a3212d"
Parent: "0baed4a5-b32d-4327-b36e-441f7c2d0af7"
Template: "0baed4a5-b32d-4327-b36e-441f7c2d0af7"
Path: "/sitecore/templates/Project/click-click-launch/Sites/Site 3/FooterST/Rendering Parameters/FooterST Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0f4c3e04-2d0a-4ee4-b85a-e7af66953008"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250529T074314Z
