---
ID: "ec41b160-e2ea-4fc1-b517-9d5ff8f4eb72"
Parent: "63c790d8-b726-4223-beca-cf3945029e50"
Template: "63c790d8-b726-4223-beca-cf3945029e50"
Path: "/sitecore/templates/Project/click-click-launch/Sites/Site 3/ImageBanner/Rendering Parameters/ImageBanner Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "48ed47b1-b95a-45c4-9d36-6edf5cad5797"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250604T125658Z
