---
ID: "91118036-da23-4ca6-aeb1-867aa1b8d317"
Parent: "d18efc57-78a0-4524-bc30-8c62b2e63f2f"
Template: "d18efc57-78a0-4524-bc30-8c62b2e63f2f"
Path: "/sitecore/templates/Project/click-click-launch/Components/Page Content/Topic Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{7BCC6B50-EA9E-457D-B232-C5CEE2090B9F}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240606T192459Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0442255f-3c02-4396-bd4a-5e5164ccd5fa"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250303T215232Z
