---
ID: "daae3f9f-be53-4862-95ee-2a92205980d5"
Parent: "8ef58813-19f7-495d-b8e5-bf9144a3ba32"
Template: "8ef58813-19f7-495d-b8e5-bf9144a3ba32"
Path: "/sitecore/templates/Project/click-click-launch/Components/Testimonials/Rendering Parameters/CustomerTestimonials Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ebfa48e4-f479-45e8-a695-4c81d0abab6a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\richard.seal@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250213T213137Z
