---
ID: "443ea3a5-d3bd-46a9-9255-931f1966e3fa"
Parent: "ae72ce09-6293-486f-b290-a0d5eecf1e63"
Template: "ae72ce09-6293-486f-b290-a0d5eecf1e63"
Path: "/sitecore/templates/Project/click-click-launch/Signup Banner/Rendering Parameters/SignupBanner Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "eeb8455e-601b-48c1-a596-5cfa329e7099"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\chamodi.samarawickrama@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250523T144950Z
