---
ID: "a585523b-3969-4e1f-b7ee-7c87b4d3b9c6"
Parent: "2706fa42-a9b2-43f4-8be7-479245b59a61"
Template: "2706fa42-a9b2-43f4-8be7-479245b59a61"
Path: "/sitecore/templates/Project/click-click-launch/Components/Hero Sections/Rendering Parameters/Hero Sections Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "57ed2065-d003-49f7-892a-7fd5b05428d0"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\richard.seal@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250214T173736Z
